resilience4j:
  circuitbreaker:
    instances:
      priceService:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        maxWaitDurationInHalfOpenState: 5s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    instances:
      priceService:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s